---

- name: Set managed installs
  set_fact:
        macos_munki_localonlymanifest__managed_installs_list:
                - "{{ macos_munki_localonlymanifest__managed_installs_adium | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_teamviewer | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_adobeacrobatpro | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_adobeaftereffects | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_adobeanimate | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_adobeaudition | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_adobebridge | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_adobecharacteranimator | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_adobedreamweaver | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_adobefireworks | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_adobeflashbuilder | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_adobeflashplayer | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_adobefuse | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_adobegamingsdk | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_adobeillustrator | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_adobeincopy | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_adobeindesign | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_adobelightroom | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_adobemediaencoder | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_adobemuse | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_adobephotoshop | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_adobeprelude | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_adobepremierepro | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_adobescout | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_adobespeedgrade | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_atom | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_audacity | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_autopkg | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_bibdesk | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_canonpsprinterdriver | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_ciscoanyconnect | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_ciscojabber | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_citrixreceiver | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_crashplan | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_createuserpkg | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_cyberduck | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_endnote | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_evernote | default('')}}"
                - "{{ macos_munki_localonlymanifest__managed_installs_f5transkript | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_facter | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_fiji | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_filemakerpro | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_flux | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_freemind | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_garageband | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_geneious | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_gimp | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_googlechrome | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_googleearth | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_hewlettpackardprinterdrivers | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_imovie | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_inkscape | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_iterm2 | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_karabiner | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_keynote | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_latexit | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_libreoffice | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_mactex | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_mactracker | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_mathematica | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_matlab | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_maxqda | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_mendeleydesktop | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_microsoftremotedesktop | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_msexcel2016 | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_msonenote2016 | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_msoutlook2016 | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_mspowerpoint2016 | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_msword2016 | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_nomad | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_numbers | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_omeroinsight | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_oraclejava8jdk | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_oraclejava8jre | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_other01 | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_other02 | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_other03 | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_other04 | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_other05 | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_other06 | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_other07 | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_other08 | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_other09 | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_other10 | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_pages | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_papers | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_prism | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_processing | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_r | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_rstudio | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_silverlight | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_skype | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_slack | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_spotify | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_spss | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_suspiciouspackage | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_switchdrive | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_symantecendpointprotection | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_texshop | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_vienna | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_virtualbox | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_vlc | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_xquartz | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_installs_zotero | default('') }}"

- name: Clean up lists
  set_fact:
        macos_munki_localonlymanifest__managed_installs_list: "{{ macos_munki_localonlymanifest__managed_installs_list | unique | difference('') }}"
